config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  scope path: '/api' do
    api_version(module: "Api::V1", path: { value: "v1" }, defaults: { format: 'json' }) do
      resources :bets, only: [:show, :update, :destroy]
      resources :monkeys, only: [:index, :show, :update, :destroy] do
        resources :bets, only: [:index]
      end
      resources :casinos do
        resources :bets, only: [:index, :create]
        resources :monkeys, only: [:index, :create]
      end
    end
  end
  resources :casinos, only: [:index, :show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  mount Sidekiq::Web => '/queue'

  root to: 'pages#home'
end

app/models/casino.rb
class Casino < ApplicationRecord
  include PowerTypes::Observable
  include LedgerizerTenant

  has_many :monkeys, dependent: :destroy
  has_many :bets, dependent: :destroy
end

# == Schema Information
#
# Table name: casinos
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/api/v1/casinos_controller.rb
class Api::V1::CasinosController < Api::V1::BaseController
  def index
    respond_with Casino.all
  end

  def show
    respond_with casino
  end

  def create
    respond_with Casino.create!(casino_params)
  end

  def update
    respond_with casino.update!(casino_params)
  end

  def destroy
    respond_with casino.destroy!
  end

  private

  def casino
    @casino ||= Casino.find_by!(id: params[:id])
  end

  def casino_params
    params.require(:casino).permit(
      :name
    )
  end
end

app/controllers/casinos_controller.rb
class CasinosController < ApplicationController
  def index; end

  def show
    @casino = Casino.find_by(id: params[:id])
    redirect_to root_path unless @casino
  end
end

app/helpers/casinos_helper.rb
module CasinosHelper
end

app/views/casinos/index.html.erb
<casino-list />

app/views/casinos/new.html.erb
<h1>Creando un casino</h1>
<%= form_with scope: :casino, url: casinos_path, local: true do |form| %>
<p>
    <%= form.label 'Edición' %><br>
    <%= form.text_field :edition %>
  </p>
  <p>
    <%= form.label 'Número de players' %><br>
    <%= form.text_field :quantity_players %>
  </p>
  <p>
    <%= form.label 'Bananas iniciales 🍌' %><br>
    <%= form.text_field :bananas %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/casinos/show.html.erb
<h1>Casinos#show</h1>
<p>Find me in app/views/casinos/show.html.erb</p>
<casino casino-id="<%= @casino.id %>"/>